spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: http://moirai-auth:8082
              predicates:
                - Path=/api/auth/**

            - id: alloc
              uri: http://moirai-alloc:8080
              predicates:
                - Path=/api/**

            - id: noti
              uri: http://notification-service:8083
              predicates:
                - Path=/noti/**
              filters:
                - StripPrefix=1

            - id: ai
              uri: http://ai-service:8000
              predicates:
                - Path=/ai/**
              filters:
                - StripPrefix=1
