server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://moirai-auth-service:8082
          predicates:
            - Path=/api/auth/**
        - id: alloc
          uri: http://moirai-core-service-dev:8080
          predicates:
            - Path=/api/**
        - id: ai
          uri: http://moirai-rag-service:8000
          predicates:
            - Path=/api/projects/**
          filters:
            - StripPrefix=1
